; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
check_tool = cppcheck
check_flags = --enable=all
monitor_speed = 115200
upload_protocol = espota
lib_deps =
  PubSubClient
build_flags = 
  -I$PROJECT_DIR/src
  -I$PROJECT_DIR/include
  -Wall -Wextra

[env:zone1]
upload_port = 192.168.0.37
build_flags = ${env.build_flags} -D USE_ZONE1_CONFIG

[env:zone3]
upload_port = 192.168.0.227
build_flags = ${env.build_flags} -D USE_ZONE3_CONFIG

; [env:soil1]
; upload_port = 192.168.0.227
; build_flags = ${env.build_flags} -D USE_SOIL1_CONFIG

; [env:soil2]
; upload_port = 192.168.0.37
; build_flags = ${env.build_flags} -D USE_SOIL2_CONFIG