// #ifndef __CONFIG_H
// #define __CONFIG_H

// adjust below as required
#define MOISTURE_SENSOR_ZONE_LOCATION "3"

#define MOISTURE_SENSOR_ID "1"
#define SENSOR_NAME "SENSOR_1"

// #define DEBUG_WSERIAL
#define MQTT_SENSOR_READ_PERIOD_SECONDS 300

#define MOVING_AVERAGE_WINDOW_SIZE 5
#define SENSOR_MOVING_AVERAGE_WINDOW_SIZE_TOPIC MQTT_PRIMARY_TOPIC "/movingAverageReadingWindowSize"
#define MAX_READINGS 256

#define RELEASE
