// #ifndef __CONFIG_H
// #define __CONFIG_H

// adjust below as required
#define MOISTURE_SENSOR_ZONE_LOCATION "1"

#define MOISTURE_SENSOR_ID "3"
#define SENSOR_NAME "SENSOR_3"

// #define DEBUG_WSERIAL
#define MQTT_SENSOR_READ_PERIOD_SECONDS 30

#define MOVING_AVERAGE_WINDOW_SIZE 5
#define SENSOR_MOVING_AVERAGE_WINDOW_SIZE_TOPIC MQTT_PRIMARY_TOPIC "/movingAverageReadingWindowSize"
#define MAX_READINGS 256

#define RELEASE
