// #ifndef __CONFIG_H
// #define __CONFIG_H

// adjust below as required
#define MOISTURE_SENSOR_ZONE_LOCATION "3"
#define ZONE_ID "3"
#define ZONE_NAME "Zone3"

#define MOISTURE_SENSOR_ID "1"

// #define DEBUG_WSERIAL
#define MQTT_SENSOR_READ_PERIOD_SECONDS 60

#define SENSOR_WARMUP_TIME_MS 15000
#define MOVING_AVERAGE_WINDOW_SIZE 5

#define MOVIG_AVERAGE_SAMPLES 40
#define MOVING_AVERAGE_DELAY_BETWEEN_READINGS_MS 7
#define MOVING_AVERAGE_WINDOW_SIZE 5

#define RELEASE
